#!/bin/sh
curr_vpn="$(systemctl list-units | tr -d '*' | awk '/wg-quick/ {print $1}')"

if [ "" = "$curr_vpn" ]; then
  echo "No running VPN. Will start one."
else
  echo "Current VPN: $curr_vpn"
  echo "systemctl stop $curr_vpn"
  systemctl stop $curr_vpn
  echo "Stopped $curr_vpn"
fi

if [ "" = "$1" ]; then
  echo "No VPN specified to start. Pass as first argument."
else
  echo "Starting wg-quick@$1"
  echo "systemctl start wg-quick@$1"
  systemctl start "wg-quick@$1"
  echo "Started wg-quick@$1"
fi
